### ISSUE TITLE
Every instance should have its own options

### ISSUE THREAD

**Issue by joelrich** [jaggedsoft/node-binance-api#392]
I was debugging an issue when I realized that node-binance-api does not support different API keys per object:

```js
const k1 = "...";
const s1 = "...";
const k2 = "...";
const s2 = "...";

const Binance = require('node-binance-api');

function create(key, secret) {
    return new Binance().options({APIKEY: key, APISECRET: secret});
}

async function test1() {
    let b1 = create(k1, s1);
    let b2 = create(k2, s2);

    console.log((await b1.futuresAccount()).totalWalletBalance);
    console.log((await b2.futuresAccount()).totalWalletBalance);
}
test1();

async function test2() {
    let b1 = create(k1, s1);
    console.log((await b1.futuresAccount()).totalWalletBalance);

    let b2 = create(k2, s2);
    console.log((await b2.futuresAccount()).totalWalletBalance);
}
test2();

```

Output:

```
112.86478416
112.86478416
571.34354018
571.34354018
```

Expected:

```
112.86478416
571.34354018
112.86478416
571.34354018
```

Interestingly, if we use the following create instead (without `new`):

```js
function create(key, secret) {
    return Binance().options({APIKEY: key, APISECRET: secret});
}
```
Then we even get:
```
112.84047182
571.34354018
571.34354018
571.34354018
```

**Comment by jaggedsoft** [comment]
This should be working as-is, but it's possible something isn't working right with the futures API, I can't see why though it.. looks like everything is done correctly. I can't test myself since I only have one account
```
const Binance = require('node-binance-api');
const instance1 = new Binance().options({
  APIKEY: '<key1>',
  APISECRET: '<secret1>'
});
const instance2 = new Binance().options({
  APIKEY: '<key2>',
  APISECRET: '<secret2>'
});
```

**Comment by joelrich** [comment]
Sorry, my mistake. I forgot that test1 and test2 are running in parallel. However, the problem still happens for the create without the `new`:
```
function create(key, secret) {
    return Binance().options({APIKEY: key, APISECRET: secret});
}
```

**Comment by joelrich** [comment]
I think it would be useful if you could print a warning when Binance is called without new and internally call new and return this object instead.

**Comment by jaggedsoft** [comment]
thanks friend, good idea

As of ECMAScript 6, this is possible with new.target.
```js
function instanceWrapper( params = {} ) {
    if ( new.target ) return api( params );
    return new api( params );
}
module.exports = instanceWrapper;
```

therefore the new constructor works any way I can think of, and we've got rid of the unnecessary call to .options(), you can pass options as constructor parameters
```js
    const Binance = require( 'node-binance-api' );
    const binance = new Binance( {verbose:true} );
    const b = Binance( {verbose:true} );
    const instance1 = Binance("options1.json");
    const instance2 = new Binance("options1.json");
```
